#!/usr/bin/env ruby
# TODO: gemify this as part of daemon gem
require 'rubygems'
require 'daemons'

ENV["APP_ROOT"] ||= File.expand_path("#{File.dirname(__FILE__)}/..")
ENV["RAILS_ENV_PATH"] ||= "#{ENV["APP_ROOT"]}/config/environment.rb"

script = "#{ENV["APP_ROOT"]}/daemons/#{ARGV[1]}"

options = { dir_mode: :normal, 
            dir: "#{ENV['APP_ROOT']}/tmp/pids", 
            log_output: true, 
            log_dir: "#{ENV['APP_ROOT']}/logs", 
            backtrace: true }

Daemons.run(script, options)
